apiVersion: v1
kind: Service
metadata:
  name: logstash-service
  namespace: monitoring
spec:
  selector:
    app: logstash
  ports:
  - protocol: TCP
    port: 5000
    nodePort: 32326
  type: NodePort

