apiVersion: v1
kind: Service
metadata:
  name: influxdb-service
  namespace: monitoring
spec:
  selector:
    app: influxdb
  ports:
  - protocol: TCP
    port: 8086
    nodePort: 32327
  type: NodePort

