apiVersion: v1
kind: Service
metadata:
  name: elasticsearch-service
  namespace: monitoring
spec:
  selector:
    app: elasticsearch
  ports:
  - protocol: TCP
    port: 9200
    nodePort: 32325
  type: NodePort
