apiVersion: v1
kind: Service
metadata:
  name: prom-service
  namespace: monitoring
spec:
  selector:
    app: prometheus
  ports:
  - protocol: TCP
    port: 9090
    nodePort: 32322
  type: NodePort
